# Generated by Django 4.0 on 2021-12-29 09:37

import django.core.validators
from django.db import migrations, models
import django_resized.forms
import positions.fields
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='direction',
            name='position',
            field=positions.fields.PositionField(blank=True, default=-1, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, size=[1000, 500], upload_to=src.base.services.get_recipe_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Изображение указания к рецепту'),
        ),
    ]
