# Generated by Django 4.0 on 2021-12-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_ingridients_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации рецепта'),
        ),
    ]
