# Generated by Django 4.0 on 2022-01-14 09:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_recipe_options_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, size=[700, 350], upload_to=src.base.services.get_direction_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Изображение указания к рецепту'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='catalog.recipe', verbose_name='Рецепт'),
        ),
    ]
