# Generated by Django 4.0 on 2022-02-09 20:31

import django.core.validators
from django.db import migrations, models
import django_resized.forms
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_direction_image_alter_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_countable',
            field=models.BooleanField(default=True, verbose_name='Исчислемая'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, size=[1000, 500], upload_to=src.base.services.get_recipe_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Изображение рецепта'),
        ),
    ]
