# Generated by Django 4.0 on 2022-05-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_follower_options'),
        ('catalog', '0006_unit_is_countable_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.recipe', verbose_name='Рецепт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to='accounts.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохранённый рецепт',
                'verbose_name_plural': 'Сохранённые рецепты',
            },
        ),
    ]
