# Generated by Django 4.0 on 2022-01-14 09:32

import django.core.validators
from django.db import migrations
import django_resized.forms
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, size=[250, 250], upload_to=src.base.services.get_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])], verbose_name='Аватар'),
        ),
    ]
