# Generated by Django 4.0 on 2022-05-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-pk'], 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
